sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater 
    point_cloud_topic: /octomap/feed
    max_range: 5.0 
    point_subsample: 1 
    padding_offset: 0.04 
    padding_scale: 4.0 
    filtered_cloud_topic: filtered_cloud
